/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as DiseaseDetectionRouteImport } from './routes/disease-detection'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as ApiPublicHooksWeatherAlertsRouteImport } from './routes/api/public/hooks/weather-alerts'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseDetectionRoute = DiseaseDetectionRouteImport.update({
  id: '/disease-detection',
  path: '/disease-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksWeatherAlertsRoute =
  ApiPublicHooksWeatherAlertsRouteImport.update({
    id: '/api/public/hooks/weather-alerts',
    path: '/api/public/hooks/weather-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/exchange': typeof ExchangeRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/prices': typeof PricesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/weather': typeof WeatherRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/weather-alerts': typeof ApiPublicHooksWeatherAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/exchange': typeof ExchangeRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/prices': typeof PricesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/weather': typeof WeatherRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/weather-alerts': typeof ApiPublicHooksWeatherAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/exchange': typeof ExchangeRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/prices': typeof PricesRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/weather': typeof WeatherRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/weather-alerts': typeof ApiPublicHooksWeatherAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/disease-detection'
    | '/exchange'
    | '/feed'
    | '/login'
    | '/moderation'
    | '/notifications'
    | '/offline'
    | '/prices'
    | '/profile'
    | '/register'
    | '/weather'
    | '/admin/content'
    | '/admin/users'
    | '/admin/'
    | '/api/public/hooks/weather-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/disease-detection'
    | '/exchange'
    | '/feed'
    | '/login'
    | '/moderation'
    | '/notifications'
    | '/offline'
    | '/prices'
    | '/profile'
    | '/register'
    | '/weather'
    | '/admin/content'
    | '/admin/users'
    | '/admin'
    | '/api/public/hooks/weather-alerts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/disease-detection'
    | '/exchange'
    | '/feed'
    | '/login'
    | '/moderation'
    | '/notifications'
    | '/offline'
    | '/prices'
    | '/profile'
    | '/register'
    | '/weather'
    | '/admin/content'
    | '/admin/users'
    | '/admin/'
    | '/api/public/hooks/weather-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DiseaseDetectionRoute: typeof DiseaseDetectionRoute
  ExchangeRoute: typeof ExchangeRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  ModerationRoute: typeof ModerationRoute
  NotificationsRoute: typeof NotificationsRoute
  OfflineRoute: typeof OfflineRoute
  PricesRoute: typeof PricesRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  WeatherRoute: typeof WeatherRoute
  ApiPublicHooksWeatherAlertsRoute: typeof ApiPublicHooksWeatherAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-detection': {
      id: '/disease-detection'
      path: '/disease-detection'
      fullPath: '/disease-detection'
      preLoaderRoute: typeof DiseaseDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/weather-alerts': {
      id: '/api/public/hooks/weather-alerts'
      path: '/api/public/hooks/weather-alerts'
      fullPath: '/api/public/hooks/weather-alerts'
      preLoaderRoute: typeof ApiPublicHooksWeatherAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DiseaseDetectionRoute: DiseaseDetectionRoute,
  ExchangeRoute: ExchangeRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  ModerationRoute: ModerationRoute,
  NotificationsRoute: NotificationsRoute,
  OfflineRoute: OfflineRoute,
  PricesRoute: PricesRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  WeatherRoute: WeatherRoute,
  ApiPublicHooksWeatherAlertsRoute: ApiPublicHooksWeatherAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
