/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as VegetableGuideRouteImport } from './routes/vegetable-guide'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as PricePredictionRouteImport } from './routes/price-prediction'
import { Route as OrganicFertilizerRouteImport } from './routes/organic-fertilizer'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as DiseaseDetectionRouteImport } from './routes/disease-detection'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CropPlannerRouteImport } from './routes/crop-planner'
import { Route as CropGuideRouteImport } from './routes/crop-guide'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as CropGuideIndexRouteImport } from './routes/crop-guide.index'
import { Route as AiBondhuIndexRouteImport } from './routes/ai-bondhu.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VegetableGuideSlugRouteImport } from './routes/vegetable-guide.$slug'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as ProfileDiseaseHistoryRouteImport } from './routes/profile.disease-history'
import { Route as PricePredictionHistoryRouteImport } from './routes/price-prediction.history'
import { Route as CropPlannerMyPlansRouteImport } from './routes/crop-planner.my-plans'
import { Route as AiBondhuPesticideRouteImport } from './routes/ai-bondhu.pesticide'
import { Route as AiBondhuDiseaseRouteImport } from './routes/ai-bondhu.disease'
import { Route as AiBondhuChatRouteImport } from './routes/ai-bondhu.chat'
import { Route as AiBondhuCalendarRouteImport } from './routes/ai-bondhu.calendar'
import { Route as AiBondhuCalculatorRouteImport } from './routes/ai-bondhu.calculator'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProRouteImport } from './routes/admin.pro'
import { Route as AdminPricesRouteImport } from './routes/admin.prices'
import { Route as AdminNotifyRouteImport } from './routes/admin.notify'
import { Route as AdminExchangesRouteImport } from './routes/admin.exchanges'
import { Route as AdminDiseasesRouteImport } from './routes/admin.diseases'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as CropGuidePlanPlanIdRouteImport } from './routes/crop-guide.plan.$planId'
import { Route as CropGuideNewCropRouteImport } from './routes/crop-guide.new.$crop'
import { Route as ApiPublicHooksWeatherAlertsRouteImport } from './routes/api/public/hooks/weather-alerts'
import { Route as ApiPublicHooksSendScheduledBroadcastsRouteImport } from './routes/api/public/hooks/send-scheduled-broadcasts'
import { Route as ApiPublicHooksFetchGovtPricesRouteImport } from './routes/api/public/hooks/fetch-govt-prices'
import { Route as ApiPublicHooksCheckPredictionAccuracyRouteImport } from './routes/api/public/hooks/check-prediction-accuracy'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const VegetableGuideRoute = VegetableGuideRouteImport.update({
  id: '/vegetable-guide',
  path: '/vegetable-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const PricePredictionRoute = PricePredictionRouteImport.update({
  id: '/price-prediction',
  path: '/price-prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganicFertilizerRoute = OrganicFertilizerRouteImport.update({
  id: '/organic-fertilizer',
  path: '/organic-fertilizer',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseDetectionRoute = DiseaseDetectionRouteImport.update({
  id: '/disease-detection',
  path: '/disease-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CropPlannerRoute = CropPlannerRouteImport.update({
  id: '/crop-planner',
  path: '/crop-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const CropGuideRoute = CropGuideRouteImport.update({
  id: '/crop-guide',
  path: '/crop-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropGuideIndexRoute = CropGuideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CropGuideRoute,
} as any)
const AiBondhuIndexRoute = AiBondhuIndexRouteImport.update({
  id: '/ai-bondhu/',
  path: '/ai-bondhu/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VegetableGuideSlugRoute = VegetableGuideSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VegetableGuideRoute,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDiseaseHistoryRoute = ProfileDiseaseHistoryRouteImport.update({
  id: '/profile/disease-history',
  path: '/profile/disease-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PricePredictionHistoryRoute = PricePredictionHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PricePredictionRoute,
} as any)
const CropPlannerMyPlansRoute = CropPlannerMyPlansRouteImport.update({
  id: '/my-plans',
  path: '/my-plans',
  getParentRoute: () => CropPlannerRoute,
} as any)
const AiBondhuPesticideRoute = AiBondhuPesticideRouteImport.update({
  id: '/ai-bondhu/pesticide',
  path: '/ai-bondhu/pesticide',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBondhuDiseaseRoute = AiBondhuDiseaseRouteImport.update({
  id: '/ai-bondhu/disease',
  path: '/ai-bondhu/disease',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBondhuChatRoute = AiBondhuChatRouteImport.update({
  id: '/ai-bondhu/chat',
  path: '/ai-bondhu/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBondhuCalendarRoute = AiBondhuCalendarRouteImport.update({
  id: '/ai-bondhu/calendar',
  path: '/ai-bondhu/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBondhuCalculatorRoute = AiBondhuCalculatorRouteImport.update({
  id: '/ai-bondhu/calculator',
  path: '/ai-bondhu/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProRoute = AdminProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricesRoute = AdminPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotifyRoute = AdminNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExchangesRoute = AdminExchangesRouteImport.update({
  id: '/exchanges',
  path: '/exchanges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiseasesRoute = AdminDiseasesRouteImport.update({
  id: '/diseases',
  path: '/diseases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const CropGuidePlanPlanIdRoute = CropGuidePlanPlanIdRouteImport.update({
  id: '/plan/$planId',
  path: '/plan/$planId',
  getParentRoute: () => CropGuideRoute,
} as any)
const CropGuideNewCropRoute = CropGuideNewCropRouteImport.update({
  id: '/new/$crop',
  path: '/new/$crop',
  getParentRoute: () => CropGuideRoute,
} as any)
const ApiPublicHooksWeatherAlertsRoute =
  ApiPublicHooksWeatherAlertsRouteImport.update({
    id: '/api/public/hooks/weather-alerts',
    path: '/api/public/hooks/weather-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendScheduledBroadcastsRoute =
  ApiPublicHooksSendScheduledBroadcastsRouteImport.update({
    id: '/api/public/hooks/send-scheduled-broadcasts',
    path: '/api/public/hooks/send-scheduled-broadcasts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFetchGovtPricesRoute =
  ApiPublicHooksFetchGovtPricesRouteImport.update({
    id: '/api/public/hooks/fetch-govt-prices',
    path: '/api/public/hooks/fetch-govt-prices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckPredictionAccuracyRoute =
  ApiPublicHooksCheckPredictionAccuracyRouteImport.update({
    id: '/api/public/hooks/check-prediction-accuracy',
    path: '/api/public/hooks/check-prediction-accuracy',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/crop-guide': typeof CropGuideRouteWithChildren
  '/crop-planner': typeof CropPlannerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/exchange': typeof ExchangeRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/organic-fertilizer': typeof OrganicFertilizerRoute
  '/price-prediction': typeof PricePredictionRouteWithChildren
  '/prices': typeof PricesRoute
  '/register': typeof RegisterRoute
  '/vegetable-guide': typeof VegetableGuideRouteWithChildren
  '/weather': typeof WeatherRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/diseases': typeof AdminDiseasesRoute
  '/admin/exchanges': typeof AdminExchangesRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/admin/prices': typeof AdminPricesRoute
  '/admin/pro': typeof AdminProRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-bondhu/calculator': typeof AiBondhuCalculatorRoute
  '/ai-bondhu/calendar': typeof AiBondhuCalendarRoute
  '/ai-bondhu/chat': typeof AiBondhuChatRoute
  '/ai-bondhu/disease': typeof AiBondhuDiseaseRoute
  '/ai-bondhu/pesticide': typeof AiBondhuPesticideRoute
  '/crop-planner/my-plans': typeof CropPlannerMyPlansRoute
  '/price-prediction/history': typeof PricePredictionHistoryRoute
  '/profile/disease-history': typeof ProfileDiseaseHistoryRoute
  '/u/$userId': typeof UUserIdRoute
  '/vegetable-guide/$slug': typeof VegetableGuideSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ai-bondhu/': typeof AiBondhuIndexRoute
  '/crop-guide/': typeof CropGuideIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/crop-guide/new/$crop': typeof CropGuideNewCropRoute
  '/crop-guide/plan/$planId': typeof CropGuidePlanPlanIdRoute
  '/api/public/hooks/check-prediction-accuracy': typeof ApiPublicHooksCheckPredictionAccuracyRoute
  '/api/public/hooks/fetch-govt-prices': typeof ApiPublicHooksFetchGovtPricesRoute
  '/api/public/hooks/send-scheduled-broadcasts': typeof ApiPublicHooksSendScheduledBroadcastsRoute
  '/api/public/hooks/weather-alerts': typeof ApiPublicHooksWeatherAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crop-planner': typeof CropPlannerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/exchange': typeof ExchangeRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/organic-fertilizer': typeof OrganicFertilizerRoute
  '/price-prediction': typeof PricePredictionRouteWithChildren
  '/prices': typeof PricesRoute
  '/register': typeof RegisterRoute
  '/vegetable-guide': typeof VegetableGuideRouteWithChildren
  '/weather': typeof WeatherRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/diseases': typeof AdminDiseasesRoute
  '/admin/exchanges': typeof AdminExchangesRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/admin/prices': typeof AdminPricesRoute
  '/admin/pro': typeof AdminProRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-bondhu/calculator': typeof AiBondhuCalculatorRoute
  '/ai-bondhu/calendar': typeof AiBondhuCalendarRoute
  '/ai-bondhu/chat': typeof AiBondhuChatRoute
  '/ai-bondhu/disease': typeof AiBondhuDiseaseRoute
  '/ai-bondhu/pesticide': typeof AiBondhuPesticideRoute
  '/crop-planner/my-plans': typeof CropPlannerMyPlansRoute
  '/price-prediction/history': typeof PricePredictionHistoryRoute
  '/profile/disease-history': typeof ProfileDiseaseHistoryRoute
  '/u/$userId': typeof UUserIdRoute
  '/vegetable-guide/$slug': typeof VegetableGuideSlugRoute
  '/admin': typeof AdminIndexRoute
  '/ai-bondhu': typeof AiBondhuIndexRoute
  '/crop-guide': typeof CropGuideIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/crop-guide/new/$crop': typeof CropGuideNewCropRoute
  '/crop-guide/plan/$planId': typeof CropGuidePlanPlanIdRoute
  '/api/public/hooks/check-prediction-accuracy': typeof ApiPublicHooksCheckPredictionAccuracyRoute
  '/api/public/hooks/fetch-govt-prices': typeof ApiPublicHooksFetchGovtPricesRoute
  '/api/public/hooks/send-scheduled-broadcasts': typeof ApiPublicHooksSendScheduledBroadcastsRoute
  '/api/public/hooks/weather-alerts': typeof ApiPublicHooksWeatherAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/crop-guide': typeof CropGuideRouteWithChildren
  '/crop-planner': typeof CropPlannerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/disease-detection': typeof DiseaseDetectionRoute
  '/exchange': typeof ExchangeRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/organic-fertilizer': typeof OrganicFertilizerRoute
  '/price-prediction': typeof PricePredictionRouteWithChildren
  '/prices': typeof PricesRoute
  '/register': typeof RegisterRoute
  '/vegetable-guide': typeof VegetableGuideRouteWithChildren
  '/weather': typeof WeatherRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/diseases': typeof AdminDiseasesRoute
  '/admin/exchanges': typeof AdminExchangesRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/admin/prices': typeof AdminPricesRoute
  '/admin/pro': typeof AdminProRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai-bondhu/calculator': typeof AiBondhuCalculatorRoute
  '/ai-bondhu/calendar': typeof AiBondhuCalendarRoute
  '/ai-bondhu/chat': typeof AiBondhuChatRoute
  '/ai-bondhu/disease': typeof AiBondhuDiseaseRoute
  '/ai-bondhu/pesticide': typeof AiBondhuPesticideRoute
  '/crop-planner/my-plans': typeof CropPlannerMyPlansRoute
  '/price-prediction/history': typeof PricePredictionHistoryRoute
  '/profile/disease-history': typeof ProfileDiseaseHistoryRoute
  '/u/$userId': typeof UUserIdRoute
  '/vegetable-guide/$slug': typeof VegetableGuideSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ai-bondhu/': typeof AiBondhuIndexRoute
  '/crop-guide/': typeof CropGuideIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/crop-guide/new/$crop': typeof CropGuideNewCropRoute
  '/crop-guide/plan/$planId': typeof CropGuidePlanPlanIdRoute
  '/api/public/hooks/check-prediction-accuracy': typeof ApiPublicHooksCheckPredictionAccuracyRoute
  '/api/public/hooks/fetch-govt-prices': typeof ApiPublicHooksFetchGovtPricesRoute
  '/api/public/hooks/send-scheduled-broadcasts': typeof ApiPublicHooksSendScheduledBroadcastsRoute
  '/api/public/hooks/weather-alerts': typeof ApiPublicHooksWeatherAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/crop-guide'
    | '/crop-planner'
    | '/dashboard'
    | '/disease-detection'
    | '/exchange'
    | '/feed'
    | '/login'
    | '/moderation'
    | '/notifications'
    | '/offline'
    | '/organic-fertilizer'
    | '/price-prediction'
    | '/prices'
    | '/register'
    | '/vegetable-guide'
    | '/weather'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/diseases'
    | '/admin/exchanges'
    | '/admin/notify'
    | '/admin/prices'
    | '/admin/pro'
    | '/admin/reports'
    | '/admin/users'
    | '/ai-bondhu/calculator'
    | '/ai-bondhu/calendar'
    | '/ai-bondhu/chat'
    | '/ai-bondhu/disease'
    | '/ai-bondhu/pesticide'
    | '/crop-planner/my-plans'
    | '/price-prediction/history'
    | '/profile/disease-history'
    | '/u/$userId'
    | '/vegetable-guide/$slug'
    | '/admin/'
    | '/ai-bondhu/'
    | '/crop-guide/'
    | '/profile/'
    | '/crop-guide/new/$crop'
    | '/crop-guide/plan/$planId'
    | '/api/public/hooks/check-prediction-accuracy'
    | '/api/public/hooks/fetch-govt-prices'
    | '/api/public/hooks/send-scheduled-broadcasts'
    | '/api/public/hooks/weather-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crop-planner'
    | '/dashboard'
    | '/disease-detection'
    | '/exchange'
    | '/feed'
    | '/login'
    | '/moderation'
    | '/notifications'
    | '/offline'
    | '/organic-fertilizer'
    | '/price-prediction'
    | '/prices'
    | '/register'
    | '/vegetable-guide'
    | '/weather'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/diseases'
    | '/admin/exchanges'
    | '/admin/notify'
    | '/admin/prices'
    | '/admin/pro'
    | '/admin/reports'
    | '/admin/users'
    | '/ai-bondhu/calculator'
    | '/ai-bondhu/calendar'
    | '/ai-bondhu/chat'
    | '/ai-bondhu/disease'
    | '/ai-bondhu/pesticide'
    | '/crop-planner/my-plans'
    | '/price-prediction/history'
    | '/profile/disease-history'
    | '/u/$userId'
    | '/vegetable-guide/$slug'
    | '/admin'
    | '/ai-bondhu'
    | '/crop-guide'
    | '/profile'
    | '/crop-guide/new/$crop'
    | '/crop-guide/plan/$planId'
    | '/api/public/hooks/check-prediction-accuracy'
    | '/api/public/hooks/fetch-govt-prices'
    | '/api/public/hooks/send-scheduled-broadcasts'
    | '/api/public/hooks/weather-alerts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/crop-guide'
    | '/crop-planner'
    | '/dashboard'
    | '/disease-detection'
    | '/exchange'
    | '/feed'
    | '/login'
    | '/moderation'
    | '/notifications'
    | '/offline'
    | '/organic-fertilizer'
    | '/price-prediction'
    | '/prices'
    | '/register'
    | '/vegetable-guide'
    | '/weather'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/diseases'
    | '/admin/exchanges'
    | '/admin/notify'
    | '/admin/prices'
    | '/admin/pro'
    | '/admin/reports'
    | '/admin/users'
    | '/ai-bondhu/calculator'
    | '/ai-bondhu/calendar'
    | '/ai-bondhu/chat'
    | '/ai-bondhu/disease'
    | '/ai-bondhu/pesticide'
    | '/crop-planner/my-plans'
    | '/price-prediction/history'
    | '/profile/disease-history'
    | '/u/$userId'
    | '/vegetable-guide/$slug'
    | '/admin/'
    | '/ai-bondhu/'
    | '/crop-guide/'
    | '/profile/'
    | '/crop-guide/new/$crop'
    | '/crop-guide/plan/$planId'
    | '/api/public/hooks/check-prediction-accuracy'
    | '/api/public/hooks/fetch-govt-prices'
    | '/api/public/hooks/send-scheduled-broadcasts'
    | '/api/public/hooks/weather-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CropGuideRoute: typeof CropGuideRouteWithChildren
  CropPlannerRoute: typeof CropPlannerRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DiseaseDetectionRoute: typeof DiseaseDetectionRoute
  ExchangeRoute: typeof ExchangeRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  ModerationRoute: typeof ModerationRoute
  NotificationsRoute: typeof NotificationsRoute
  OfflineRoute: typeof OfflineRoute
  OrganicFertilizerRoute: typeof OrganicFertilizerRoute
  PricePredictionRoute: typeof PricePredictionRouteWithChildren
  PricesRoute: typeof PricesRoute
  RegisterRoute: typeof RegisterRoute
  VegetableGuideRoute: typeof VegetableGuideRouteWithChildren
  WeatherRoute: typeof WeatherRoute
  AiBondhuCalculatorRoute: typeof AiBondhuCalculatorRoute
  AiBondhuCalendarRoute: typeof AiBondhuCalendarRoute
  AiBondhuChatRoute: typeof AiBondhuChatRoute
  AiBondhuDiseaseRoute: typeof AiBondhuDiseaseRoute
  AiBondhuPesticideRoute: typeof AiBondhuPesticideRoute
  ProfileDiseaseHistoryRoute: typeof ProfileDiseaseHistoryRoute
  UUserIdRoute: typeof UUserIdRoute
  AiBondhuIndexRoute: typeof AiBondhuIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ApiPublicHooksCheckPredictionAccuracyRoute: typeof ApiPublicHooksCheckPredictionAccuracyRoute
  ApiPublicHooksFetchGovtPricesRoute: typeof ApiPublicHooksFetchGovtPricesRoute
  ApiPublicHooksSendScheduledBroadcastsRoute: typeof ApiPublicHooksSendScheduledBroadcastsRoute
  ApiPublicHooksWeatherAlertsRoute: typeof ApiPublicHooksWeatherAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vegetable-guide': {
      id: '/vegetable-guide'
      path: '/vegetable-guide'
      fullPath: '/vegetable-guide'
      preLoaderRoute: typeof VegetableGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-prediction': {
      id: '/price-prediction'
      path: '/price-prediction'
      fullPath: '/price-prediction'
      preLoaderRoute: typeof PricePredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organic-fertilizer': {
      id: '/organic-fertilizer'
      path: '/organic-fertilizer'
      fullPath: '/organic-fertilizer'
      preLoaderRoute: typeof OrganicFertilizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-detection': {
      id: '/disease-detection'
      path: '/disease-detection'
      fullPath: '/disease-detection'
      preLoaderRoute: typeof DiseaseDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-planner': {
      id: '/crop-planner'
      path: '/crop-planner'
      fullPath: '/crop-planner'
      preLoaderRoute: typeof CropPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-guide': {
      id: '/crop-guide'
      path: '/crop-guide'
      fullPath: '/crop-guide'
      preLoaderRoute: typeof CropGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-guide/': {
      id: '/crop-guide/'
      path: '/'
      fullPath: '/crop-guide/'
      preLoaderRoute: typeof CropGuideIndexRouteImport
      parentRoute: typeof CropGuideRoute
    }
    '/ai-bondhu/': {
      id: '/ai-bondhu/'
      path: '/ai-bondhu'
      fullPath: '/ai-bondhu/'
      preLoaderRoute: typeof AiBondhuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vegetable-guide/$slug': {
      id: '/vegetable-guide/$slug'
      path: '/$slug'
      fullPath: '/vegetable-guide/$slug'
      preLoaderRoute: typeof VegetableGuideSlugRouteImport
      parentRoute: typeof VegetableGuideRoute
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/disease-history': {
      id: '/profile/disease-history'
      path: '/profile/disease-history'
      fullPath: '/profile/disease-history'
      preLoaderRoute: typeof ProfileDiseaseHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-prediction/history': {
      id: '/price-prediction/history'
      path: '/history'
      fullPath: '/price-prediction/history'
      preLoaderRoute: typeof PricePredictionHistoryRouteImport
      parentRoute: typeof PricePredictionRoute
    }
    '/crop-planner/my-plans': {
      id: '/crop-planner/my-plans'
      path: '/my-plans'
      fullPath: '/crop-planner/my-plans'
      preLoaderRoute: typeof CropPlannerMyPlansRouteImport
      parentRoute: typeof CropPlannerRoute
    }
    '/ai-bondhu/pesticide': {
      id: '/ai-bondhu/pesticide'
      path: '/ai-bondhu/pesticide'
      fullPath: '/ai-bondhu/pesticide'
      preLoaderRoute: typeof AiBondhuPesticideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-bondhu/disease': {
      id: '/ai-bondhu/disease'
      path: '/ai-bondhu/disease'
      fullPath: '/ai-bondhu/disease'
      preLoaderRoute: typeof AiBondhuDiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-bondhu/chat': {
      id: '/ai-bondhu/chat'
      path: '/ai-bondhu/chat'
      fullPath: '/ai-bondhu/chat'
      preLoaderRoute: typeof AiBondhuChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-bondhu/calendar': {
      id: '/ai-bondhu/calendar'
      path: '/ai-bondhu/calendar'
      fullPath: '/ai-bondhu/calendar'
      preLoaderRoute: typeof AiBondhuCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-bondhu/calculator': {
      id: '/ai-bondhu/calculator'
      path: '/ai-bondhu/calculator'
      fullPath: '/ai-bondhu/calculator'
      preLoaderRoute: typeof AiBondhuCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pro': {
      id: '/admin/pro'
      path: '/pro'
      fullPath: '/admin/pro'
      preLoaderRoute: typeof AdminProRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prices': {
      id: '/admin/prices'
      path: '/prices'
      fullPath: '/admin/prices'
      preLoaderRoute: typeof AdminPricesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notify': {
      id: '/admin/notify'
      path: '/notify'
      fullPath: '/admin/notify'
      preLoaderRoute: typeof AdminNotifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exchanges': {
      id: '/admin/exchanges'
      path: '/exchanges'
      fullPath: '/admin/exchanges'
      preLoaderRoute: typeof AdminExchangesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diseases': {
      id: '/admin/diseases'
      path: '/diseases'
      fullPath: '/admin/diseases'
      preLoaderRoute: typeof AdminDiseasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/crop-guide/plan/$planId': {
      id: '/crop-guide/plan/$planId'
      path: '/plan/$planId'
      fullPath: '/crop-guide/plan/$planId'
      preLoaderRoute: typeof CropGuidePlanPlanIdRouteImport
      parentRoute: typeof CropGuideRoute
    }
    '/crop-guide/new/$crop': {
      id: '/crop-guide/new/$crop'
      path: '/new/$crop'
      fullPath: '/crop-guide/new/$crop'
      preLoaderRoute: typeof CropGuideNewCropRouteImport
      parentRoute: typeof CropGuideRoute
    }
    '/api/public/hooks/weather-alerts': {
      id: '/api/public/hooks/weather-alerts'
      path: '/api/public/hooks/weather-alerts'
      fullPath: '/api/public/hooks/weather-alerts'
      preLoaderRoute: typeof ApiPublicHooksWeatherAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-scheduled-broadcasts': {
      id: '/api/public/hooks/send-scheduled-broadcasts'
      path: '/api/public/hooks/send-scheduled-broadcasts'
      fullPath: '/api/public/hooks/send-scheduled-broadcasts'
      preLoaderRoute: typeof ApiPublicHooksSendScheduledBroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fetch-govt-prices': {
      id: '/api/public/hooks/fetch-govt-prices'
      path: '/api/public/hooks/fetch-govt-prices'
      fullPath: '/api/public/hooks/fetch-govt-prices'
      preLoaderRoute: typeof ApiPublicHooksFetchGovtPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-prediction-accuracy': {
      id: '/api/public/hooks/check-prediction-accuracy'
      path: '/api/public/hooks/check-prediction-accuracy'
      fullPath: '/api/public/hooks/check-prediction-accuracy'
      preLoaderRoute: typeof ApiPublicHooksCheckPredictionAccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDiseasesRoute: typeof AdminDiseasesRoute
  AdminExchangesRoute: typeof AdminExchangesRoute
  AdminNotifyRoute: typeof AdminNotifyRoute
  AdminPricesRoute: typeof AdminPricesRoute
  AdminProRoute: typeof AdminProRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDiseasesRoute: AdminDiseasesRoute,
  AdminExchangesRoute: AdminExchangesRoute,
  AdminNotifyRoute: AdminNotifyRoute,
  AdminPricesRoute: AdminPricesRoute,
  AdminProRoute: AdminProRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CropGuideRouteChildren {
  CropGuideIndexRoute: typeof CropGuideIndexRoute
  CropGuideNewCropRoute: typeof CropGuideNewCropRoute
  CropGuidePlanPlanIdRoute: typeof CropGuidePlanPlanIdRoute
}

const CropGuideRouteChildren: CropGuideRouteChildren = {
  CropGuideIndexRoute: CropGuideIndexRoute,
  CropGuideNewCropRoute: CropGuideNewCropRoute,
  CropGuidePlanPlanIdRoute: CropGuidePlanPlanIdRoute,
}

const CropGuideRouteWithChildren = CropGuideRoute._addFileChildren(
  CropGuideRouteChildren,
)

interface CropPlannerRouteChildren {
  CropPlannerMyPlansRoute: typeof CropPlannerMyPlansRoute
}

const CropPlannerRouteChildren: CropPlannerRouteChildren = {
  CropPlannerMyPlansRoute: CropPlannerMyPlansRoute,
}

const CropPlannerRouteWithChildren = CropPlannerRoute._addFileChildren(
  CropPlannerRouteChildren,
)

interface PricePredictionRouteChildren {
  PricePredictionHistoryRoute: typeof PricePredictionHistoryRoute
}

const PricePredictionRouteChildren: PricePredictionRouteChildren = {
  PricePredictionHistoryRoute: PricePredictionHistoryRoute,
}

const PricePredictionRouteWithChildren = PricePredictionRoute._addFileChildren(
  PricePredictionRouteChildren,
)

interface VegetableGuideRouteChildren {
  VegetableGuideSlugRoute: typeof VegetableGuideSlugRoute
}

const VegetableGuideRouteChildren: VegetableGuideRouteChildren = {
  VegetableGuideSlugRoute: VegetableGuideSlugRoute,
}

const VegetableGuideRouteWithChildren = VegetableGuideRoute._addFileChildren(
  VegetableGuideRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CropGuideRoute: CropGuideRouteWithChildren,
  CropPlannerRoute: CropPlannerRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DiseaseDetectionRoute: DiseaseDetectionRoute,
  ExchangeRoute: ExchangeRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  ModerationRoute: ModerationRoute,
  NotificationsRoute: NotificationsRoute,
  OfflineRoute: OfflineRoute,
  OrganicFertilizerRoute: OrganicFertilizerRoute,
  PricePredictionRoute: PricePredictionRouteWithChildren,
  PricesRoute: PricesRoute,
  RegisterRoute: RegisterRoute,
  VegetableGuideRoute: VegetableGuideRouteWithChildren,
  WeatherRoute: WeatherRoute,
  AiBondhuCalculatorRoute: AiBondhuCalculatorRoute,
  AiBondhuCalendarRoute: AiBondhuCalendarRoute,
  AiBondhuChatRoute: AiBondhuChatRoute,
  AiBondhuDiseaseRoute: AiBondhuDiseaseRoute,
  AiBondhuPesticideRoute: AiBondhuPesticideRoute,
  ProfileDiseaseHistoryRoute: ProfileDiseaseHistoryRoute,
  UUserIdRoute: UUserIdRoute,
  AiBondhuIndexRoute: AiBondhuIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ApiPublicHooksCheckPredictionAccuracyRoute:
    ApiPublicHooksCheckPredictionAccuracyRoute,
  ApiPublicHooksFetchGovtPricesRoute: ApiPublicHooksFetchGovtPricesRoute,
  ApiPublicHooksSendScheduledBroadcastsRoute:
    ApiPublicHooksSendScheduledBroadcastsRoute,
  ApiPublicHooksWeatherAlertsRoute: ApiPublicHooksWeatherAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
